name: Build and Publish image to Docker Hub
on:
  push:
    branches:
      - main
    paths:
      - 'api/Dockerfile'
      - 'front-end-nextjs/Dockerfile'

jobs:
  publish_images:
    runs-on: ubuntu-latest
    # steps:
    #   - name: checkout
    #     uses: actions/checkout@v4
    #   - name: build image
    #     run: |
    #       docker build ./api/ -t rishabkumar7/devops-qr-code-backend:latest
    #       docker build ./front-end-nextjs/ -t rishabkumar7/devops-qr-code-frontend:latest
    #   - name: push image to docker hub
    #     run: |
    #       docker login -u rishabkumar7 -p ${{ secrets.DOCKER_HUB_TOKEN }}
    #       docker push rishabkumar7/devops-qr-code-backend:latest
    #       docker push rishabkumar7/devops-qr-code-frontend:latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the hello-world Docker image
      run: |
        #echo $SC | docker login ghcr.io -u Kritika786 --password-stdin
        #echo $SC | docker login -u Kritika786 --password-stdin
         echo ${{ secrets.SC }} | docker login -u ${{ github.repository_owner }} --password-stdin ghcr.io
      env:
        SC: ${{ secrets.SC }}
    - name: Push image
      run: |
        docker build ./api/ --tag ghcr.io/kritika786/aws-devops-capstone-project/backend/backend:latest
        docker run ghcr.io/kritika786/aws-devops-capstone-project/backend/backend:latest
        docker push ghcr.io/kritika786/aws-devops-capstone-project/backend/backend:latest




        
